version: 2
project_name: torvecode
before:
  hooks:
builds:
  - env:
      - CGO_ENABLED=0
    binary: torve
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/jisunahamed/torvecode/internal/version.Version={{.Version}}
    main: ./cmd/torve

archives:
  - format: tar.gz
    name_template: >-
      torve-
      {{- if eq .Os "darwin" }}mac-
      {{- else if eq .Os "windows" }}windows-
      {{- else if eq .Os "linux" }}linux-{{end}}
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "#86" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "0.0.0-{{ .Timestamp }}"
brews:
  - repository:
      owner: torveai
      name: homebrew-tap
    homepage: "https://torveai.com/torvecode"
    description: "Torve AI coding agent for the terminal"
    license: "MIT"
nfpms:
  - maintainer: Torve AI
    description: Torve AI coding agent for the terminal
    formats:
      - deb
      - rpm
    file_name_template: >-
      {{ .ProjectName }}-
      {{- if eq .Os "darwin" }}mac
      {{- else }}{{ .Os }}{{ end }}-{{ .Arch }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^doc:"
      - "^test:"
      - "^ci:"
      - "^ignore:"
      - "^example:"
      - "^wip:"
