#!/usr/bin/env bash
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

requested_version=${VERSION:-latest}
os=$(uname -s | tr '[:upper:]' '[:lower:]')
arch=$(uname -m)

case "$os" in
  darwin) os=mac ;;
  linux) ;;
  *) printf "%bUnsupported OS: %s%b\n" "$RED" "$os" "$NC"; exit 1 ;;
esac

case "$arch" in
  x86_64|amd64) arch=x86_64 ;;
  arm64|aarch64) arch=arm64 ;;
  *) printf "%bUnsupported architecture: %s%b\n" "$RED" "$arch" "$NC"; exit 1 ;;
esac

archive="torve-${os}-${arch}.tar.gz"
if [[ "$requested_version" == latest ]]; then
  url="https://github.com/jisunahamed/torvecode/releases/latest/download/${archive}"
else
  version=${requested_version#v}
  url="https://github.com/jisunahamed/torvecode/releases/download/v${version}/${archive}"
fi

install_dir=${TORVE_INSTALL_DIR:-"$HOME/.torvecode/bin"}
temporary_dir=$(mktemp -d "${TMPDIR:-/tmp}/torve-install.XXXXXX")
trap 'rm -rf "$temporary_dir"' EXIT

printf "%bDownloading Torvecode for %s/%s...%b\n" "$GREEN" "$os" "$arch" "$NC"
curl --fail --location --progress-bar "$url" --output "$temporary_dir/$archive"
tar -xzf "$temporary_dir/$archive" -C "$temporary_dir"
install -d "$install_dir"
install -m 0755 "$temporary_dir/torve" "$install_dir/torve"

if [[ ":$PATH:" != *":$install_dir:"* ]]; then
  printf "%bAdd Torvecode to PATH:%b\n  export PATH=\"%s:\$PATH\"\n" "$YELLOW" "$NC" "$install_dir"
fi

if [[ ${GITHUB_ACTIONS:-} == true && -n ${GITHUB_PATH:-} ]]; then
  printf "%s\n" "$install_dir" >> "$GITHUB_PATH"
fi

printf "%bInstalled %s%b\n" "$GREEN" "$install_dir/torve" "$NC"
